/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AdventureBegins: typeof import('./src/components/Icons/AdventureBegins.vue')['default']
    DoubleHeart: typeof import('./src/components/Icons/DoubleHeart.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElCalendar: typeof import('element-plus/es')['ElCalendar']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElCountdown: typeof import('element-plus/es')['ElCountdown']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    FooterApp: typeof import('./src/components/Footer/FooterApp.vue')['default']
    HeaderApp: typeof import('./src/components/Header/HeaderApp.vue')['default']
    HeaderMobileNav: typeof import('./src/components/Header/HeaderMobileNav.vue')['default']
    HeaderNav: typeof import('./src/components/Header/HeaderNav.vue')['default']
    MainAboutUs: typeof import('./src/components/MainApp/MainAboutUs.vue')['default']
    MainApp: typeof import('./src/components/MainApp/MainApp.vue')['default']
    MainCalendar: typeof import('./src/components/MainApp/MainCalendar.vue')['default']
    MainHero: typeof import('./src/components/MainApp/MainHero/MainHero.vue')['default']
    MainHeroBackground: typeof import('./src/components/MainApp/MainHero/MainHeroBackground.vue')['default']
    UContainer: typeof import('./src/components/UI/UContainer.vue')['default']
    UDivider: typeof import('./src/components/UI/UDivider.vue')['default']
  }
}
